# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'Flash Chat iOS13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  # Pods for Flash Chat iOS13
end
